# Generated by Django 3.2.12 on 2022-05-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
    ]
